sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
  - "3.2.1"
  - "3.4.4"
  - development

install:
  - haxelib install travix
  - haxelib run travix install

script:
  - if [ "$TRAVIS_HAXE_VERSION" == "development" ]; then haxelib run travix interp; fi
  - haxelib run travix neko
  - haxelib run travix python
  - haxelib run travix node
  - haxelib run travix java
  - if ! [ "$TRAVIS_HAXE_VERSION" == "3.2.1" ]; then haxelib run travix cpp; fi
  # Travix executes tests without --debug for c#, which leads to losing line numbers
  # - haxelib run travix cs
  - if [ "$TRAVIS_HAXE_VERSION" == "development" ]; then haxelib run travix php; fi
  #Invalid lua setup on OSX. See https://github.com/back2dos/travix/issues/78
  - if [ `uname` = "Linux" ] && ! [ "$TRAVIS_HAXE_VERSION" == "3.2.1" ]; then haxelib run travix lua; fi;